# Generated by Django 3.1.4 on 2020-12-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201230_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_description',
            field=models.TextField(),
        ),
    ]
