# Generated by Django 3.1.4 on 2020-12-30 17:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201230_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
