# Generated by Django 3.1.4 on 2020-12-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201230_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
