# Generated by Django 3.1.4 on 2020-12-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0005_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_description', models.TextField()),
                ('food_price', models.CharField(max_length=20)),
                ('food_slug', models.CharField(max_length=50)),
            ],
        ),
    ]
